grupa_projekt_homepage:
    path:     /
    defaults: { _controller: GrupaProjektBundle:Index:showIndex }


car:
    path:     /sc
    defaults: { _controller: GrupaProjektBundle:Supercars:sc}

supercars_marki:
    path:     /sc/{make}
    defaults: { _controller: GrupaProjektBundle:Supercars:show}


admin_dodaj:
    path:     /admin/dodaj
    defaults: { _controller: GrupaProjektBundle:Admin:dodajFilm }

admin_usun:
    path:     /admin/usun
    defaults: { _controller: GrupaProjektBundle:Admin:usunFilm }

admin_panel:
    path:     /admin/panel
    defaults: { _controller: GrupaProjektBundle:Admin:panel }

logowanie:
    path:     /logowanie
    defaults: { _controller: GrupaProjektBundle:Index:logowanie }
recenzja:
    path:    /zalogowany/recenzja
    defaults: { _controller: GrupaProjektBundle:Recenzja:showRecenzjaLog }

pokaz_koszyk:
    path:     /Koszyk
    defaults: { _controller: GrupaProjektBundle:Koszyk:pokazKoszyk }

show_zamowienia:
    path:     /Zamowienia
    defaults: { _controller: GrupaProjektBundle:Zamowienia:showZamowienia }

en:
    path:     /En
    defaults: { _controller: GrupaProjektBundle:En:en }
